# Generated by Django 4.1.7 on 2023-03-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.TextField()),
                ('data_insercao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
