# Generated by Django 4.2 on 2023-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_post_alter_item_image_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body2',
        ),
        migrations.AddField(
            model_name='post',
            name='body1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
