# Generated by Django 4.2 on 2023-04-10 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_rename_body_post_body2_post_body1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
