# Generated by Django 4.2 on 2023-04-12 14:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_post_body3_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_with_photo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
