# Generated by Django 4.2 on 2023-04-24 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_category_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_with_photo',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Descrição longa / com foto'),
        ),
    ]
