# Generated by Django 4.2 on 2023-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_item_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Deseja publicar?'),
        ),
    ]
