# Generated by Django 4.2 on 2023-04-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_grupoacesso_publicador'),
        ('item', '0016_alter_item_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grupo_acesso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.grupoacesso'),
        ),
    ]
