# Generated by Django 4.2 on 2023-05-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categorias'},
        ),
    ]
