# Generated by Django 4.2 on 2023-05-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0013_alter_menu_options_menu_grupo_acesso_delete_setor'),
        ('item', '0021_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.menu', verbose_name='Menu'),
        ),
        migrations.AddField(
            model_name='item',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.submenu', verbose_name='SubMenu'),
        ),
    ]
