# Generated by Django 4.1.7 on 2023-03-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil_acesso',
        ),
        migrations.DeleteModel(
            name='GrupoAcesso',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
