# Generated by Django 4.2 on 2023-04-10 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
