# Generated by Django 4.2 on 2023-04-11 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='testar',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
