# Generated by Django 4.1.7 on 2023-03-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0002_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_acesso', models.IntegerField()),
                ('nome_grupo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Grupos de acesso',
                'ordering': ('nome_grupo',),
            },
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ('nome', 'menu'), 'verbose_name_plural': 'SubMenus'},
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drt', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('perfil_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.grupoacesso')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'ordering': ('perfil_acesso', 'nome'),
            },
        ),
    ]
