# Generated by Django 4.1.7 on 2023-03-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0005_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
