# Generated by Django 4.2 on 2023-04-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_perfil_acesso'),
        ('novo_portal_dva', '0007_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoAoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_accessed', models.BooleanField(default=False)),
                ('fk_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
