# Generated by Django 4.2 on 2023-04-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0008_acessoaomenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessoaomenu',
            old_name='user',
            new_name='fk_user',
        ),
    ]
