# Generated by Django 4.2 on 2023-04-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0009_rename_user_acessoaomenu_fk_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessoaomenu',
            options={'verbose_name_plural': 'Acesso aos Menus'},
        ),
    ]
