# Generated by Django 4.2 on 2023-04-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0011_submenu3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.menu')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novo_portal_dva.submenu')),
            ],
            options={
                'verbose_name_plural': 'SubMenus 3',
                'ordering': ('nome', 'menu', 'submenu'),
            },
        ),
    ]
