# Generated by Django 4.2 on 2023-04-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_grupoacesso_grupo_acesso'),
        ('novo_portal_dva', '0012_alter_menu_nome_alter_submenu_nome_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('nome', 'grupo_acesso'), 'verbose_name_plural': 'Menus'},
        ),
        migrations.AddField(
            model_name='menu',
            name='grupo_acesso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.grupoacesso'),
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
