# Generated by Django 4.2 on 2023-05-16 15:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novo_portal_dva', '0014_submenu_grupo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu3',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submenu3',
            name='created_by',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submenu3',
            name='description_with_photo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
