# Generated by Django 4.1.7 on 2023-03-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Logg',
        ),
    ]
