# Generated by Django 4.1.7 on 2023-03-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rename_log_logg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logg',
            new_name='LogRegistro',
        ),
    ]
