# Generated by Django 4.1.7 on 2023-03-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_rename_logg_logregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogRegistro',
        ),
    ]
