# Generated by Django 4.1.7 on 2023-04-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAcessoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe_acesso', models.IntegerField()),
                ('fk_perfil_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.grupoacesso')),
            ],
            options={
                'verbose_name_plural': 'Detalhes Grupo de Acesso',
                'ordering': ('fk_perfil_acesso',),
            },
        ),
    ]
