# Generated by Django 4.2 on 2023-04-11 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_grupoacessodetalhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
