# Generated by Django 4.2 on 2023-04-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descricao',
        ),
    ]
