# Generated by Django 4.2 on 2023-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_usuario_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('nome',), 'verbose_name': 'usuario', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil_acesso',
            field=models.CharField(max_length=100),
        ),
    ]
