# Generated by Django 4.2 on 2023-04-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_options_alter_usuario_perfil_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil_acesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.grupoacesso'),
        ),
    ]
