# Generated by Django 4.2 on 2023-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_perfil_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoacesso',
            name='grupo_acesso',
            field=models.IntegerField(default=2),
        ),
    ]
