# Generated by Django 4.2 on 2023-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_grupoacesso_grupo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoacesso',
            name='publicador',
            field=models.BooleanField(default=False),
        ),
    ]
